image: openjdk:11

variables:
  GRADLE_USER_HOME: .gradle-cache

stages:
  - build
  - test

cache:
  paths:
    - .gradle-cache

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew check